spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://localhost:5433/drivers
    username: postgres
    password: 100369707
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    drop-first: true

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update

server:
  port: 8081